version: '3.9'

services:
  java_db:
    container_name: 'parking-control-db'
    image: 'postgres:12' # Compatible with most operating systems
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'parking-control-db'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }