version: '3.9'

services:
  java_db:
    container_name: 'parking-control-db'
    image: 'postgres:12' # Compatible with most operating systems
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }